name: matrix-sized
version: "0.2.0"
category: "Math"
synopsis:    "Haskell matrix library with interface to C++ linear algebra libraries."
description: "A Haskell implementation of matrices with statically known sizes.
                The library also comes with the bindings to high performance
                C++ linear algebra libraries such as Eigen v3.3.9 and Spectra v0.9.0."
license: "BSD-3-Clause"
author: "Kai Zhang"
copyright: "(c) 2020-2021 Kai Zhang"
maintainer: "kai@kzhang.org"

ghc-options: -Wall

extra-source-files:
  - cbits/*.h

  - eigen3/Eigen/*
  - eigen3/Eigen/src/**/*.h
  - eigen3/Eigen/src/**/**/*.h
  - eigen3/Eigen/src/**/**/**/*.h

  - spectra/Spectra/*.h
  - spectra/Spectra/**/*.h
  - spectra/Spectra/**/**/*.h

  - README.md
  - ChangeLog.md

flags:
  parallel:
    description: Enable multithreading
    manual: true
    default: false

default-extensions: StrictData

library:
  source-dirs:
    - src
  exposed-modules:
    - Data.Matrix.Static.Dense
    - Data.Matrix.Static.Dense.Mutable
    - Data.Matrix.Static.Sparse
    - Data.Matrix.Static.Sparse.Mutable
    - Data.Matrix.Static.LinearAlgebra
    - Data.Matrix.Static.LinearAlgebra.Types
    - Data.Matrix.Static.Generic
    - Data.Matrix.Static.Generic.Mutable
    - Data.Matrix.Static.IO
    - Data.Matrix.Dynamic

  other-modules: 
    - Data.Matrix.Static.Internal
    - Data.Matrix.Static.LinearAlgebra.Internal

  dependencies:
    - base >= 4.10 && < 5
    - bytestring
    - bytestring-lexing
    - double-conversion
    - deepseq
    - conduit
    - primitive >= 0.6.4.0
    - singletons
    - vector >= 0.11
    - flat

  include-dirs:
    - eigen3
    - spectra
    - cbits

  when:
  - condition: flag(parallel)
    ld-options:
    - -fopenmp
    cc-options:
    - -fopenmp
    cxx-options:
    - -fopenmp
    - -std=c++11

  cxx-sources:
    - cbits/*.cpp
  cxx-options:
    - -std=c++11

  extra-libraries: stdc++

tests:
  test:
    main: "Main.hs"
    ghc-options: "-threaded"

    source-dirs:
      - tests

    other-modules:
      - Test.Base
      - Test.LinearAlgebra
      - Test.Utils

    dependencies:
      - base
      - conduit
      - data-ordlist
      - matrix-sized
      - ieee754
      - flat
      - singletons
      - tasty
      - tasty-quickcheck
      - vector

    #ld-options: "-fopenmp"

benchmarks:
  bench:
    main: "Main.hs"

    source-dirs:
      - benchmark

    dependencies:
      - base
      - matrix-sized
      - singletons
      - vector
      - weigh
      - deepseq

github: kaizhang/matrix-sized
